# Generated by Django 5.2.5 on 2025-08-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="productid",
            field=models.IntegerField(unique=True),
        ),
    ]
