# Generated by Django 5.2.5 on 2025-08-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_book_productid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="category",
        ),
    ]
